server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_database?createDatabaseIfNotExist=true
    username: root
    password: B@ttEr84
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
